name: Atualizar dados Yahoo Finance

on:
  schedule:
    - cron: '*/1 * * * *'  # TESTE: Executa a cada 1 minuto
  workflow_dispatch:       # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log de teste
        run: echo "✅ Funcionou em $(date +'%Y-%m-%d %H:%M:%S')"