name: Atualizar dados Yahoo Finance

on:
  schedule:
    - cron: '15 18 * * *'  # Todos os dias às 18:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script para extrair dados
        run: python get_data.py

      - name: Commit e push dos dados atualizados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add dados/sp500.csv
          git commit -m "Atualização diária automática do S&P 500" || echo "Sem alterações"
          git push
